### ISSUE TITLE
Use nf-core download

### ISSUE THREAD

**Issue by ewels** [NationalGenomicsInfrastructure/irma-provision#324]
* [x] Install `nf-core` python package
    * GitHub: https://github.com/nf-core/tools
    * PyPI: https://pypi.org/project/nf-core/
    * Conda: https://bioconda.github.io/recipes/nf-core/README.html
* [x] `nf-core download rnaseq --singularity --compress none`
    * Downloads everything into a folder
* [x] Add custom config file in addition which does a couple of extra tweaks
* [x] Bring back `-profile uppmax`
* [x] Try to make it so that `rnaseq` is a variable, so that we can run this for a list of desired nf-core pipelines.

**Comment by ewels** [comment]
NB: Needs `nf-core` tools and nextflow installed so that Ansible can use it.. ie. they need to be available in the environment within which Ansible runs.

This means that we can't have a role for installing these tools _within_ the playbook. It has to happen first.

**Comment by johandahlberg** [comment]
Just pitching in here. If you know where you install the binaries/scripts, it shouldn't be a problem to first install `nf-core` and then use the nf-core command from the same role/playbook.

**Comment by aanil** [comment]
Added the pull request which addresses the issue!
