### ISSUE TITLE
Remove custom neutronstar config once the uppmax-specific stuff is put in to nf-core/configs

### ISSUE THREAD

**Issue by aanil** [NationalGenomicsInfrastructure/irma-provision#335]

**Comment by ewels** [comment]
This specifically refers to this discussion: https://github.com/NationalGenomicsInfrastructure/irma-provision/pull/332#discussion_r374552509

In short, there are some uppmax-specific config options for just neutronstar that we need. However, this can be handled by nf-core/configs still.

@remiolsen needs to add these extra files to nf-core/configs and update the pipeline to import them, then we can remove this custom config file in the deployment.

**Comment by aanil** [comment]
Neutronstar has been removed from irma provision. This can, therefore, be closed.
