### ISSUE TITLE
Update sync.py to only sync the most recent staging/production environment + containers

### ISSUE THREAD

**Issue by matrulda** [NationalGenomicsInfrastructure/irma-provision#376]
To making syncing faster, we should update the sync.py to only sync the most recently deployed staging/production environment. 

While at this, one could also investigate if we really need to perform a dry-run of the rsync.

**Comment by aanil** [comment]
Updated in the PR https://github.com/NationalGenomicsInfrastructure/irma-provision/pull/380.
